### ISSUE TITLE
Z jogging using game controller stick plunges too far

### ISSUE THREAD

**Issue by BaysideCustomTC** [Sienci-Labs/gsender#496] opened 2024-03-25 05:45 UTC
I have just started using v1.4.4 today and I have been using a Logitech game controller with v1.1.7.

With v1.4.4 I have had several issues with the bit plunging into the spoil board. I had to hit the stop button - it did NOT stop automatically after plunging a few mm too far.

On one occasion I believe I saw "G21G91 Z10000 F5000" in the Console (yes, I realise this is +ve not -ve and I did not get a screenshot).

I wonder whether there was an issue with the game controller (stick 2) buffering a large # of commands and sending them all to gSender?

I have not yet determined whether this relates to joysticks only, nor what steps are needed to reproduce. I will add notes if/when I see more occurrences.

**Comment by kglovern** [comment] 2024-03-25 13:29
Duplicate of #489

**Closed by kglovern** 2024-03-25 13:29 UTC
