### ISSUE TITLE
Remote session has no access to settings

### ISSUE THREAD

**Issue by rcp1** [Sienci-Labs/gsender#464] opened 2024-01-28 22:41 UTC
Hi,

a click on the settings button in a remote sesssion will just open a black screen which one can not exit anymore. Tested on Windows 11 and Linux Debian Bookworm with gSender 1.4.1 / 1.3.10 Edge.

All other menus like Surfacing or Firmware work fine...

**Comment by rcp1** [comment] 2024-01-29 19:06
Update: Works fine if remote client uses Edge, above problem only occurs in Firefox 122.0.

**Comment by JohnOCFII** [comment] 2024-01-30 02:31
> Update: Works fine if remote client uses Edge, above problem only occurs in Firefox 122.0.

Interesting.  I can confirm this issue on both gSender 1.3.10 Edge and 1.4.1 with FireFox 122.0 on macOS.  The issue does not occur using Safari 17.3 on macOS Sonoma 14.3.

**Comment by kglovern** [comment] 2024-01-30 13:55
The problem is firefox specifically with gamepad library - we'll look into it.

**Comment by kglovern** [comment] 2024-02-05 14:37
This is fixed and will be part of the next release.

**Closed by kglovern** 2024-02-05 14:37 UTC
